controller_manager:
  ros__parameters:
    update_rate: 100

t1_a1_arm_controller:
  type: FollowJointTrajectory
  joints:
    - t1_a1_shoulder_joint
    - t1_a1_elbow_joint
    - t1_a1_wrist_1_joint
    - t1_a1_wrist_2_joint
    - t1_a1_wrist_3_joint
  allow_partial_joints_goal: true

t1_a2_arm_controller:
  type: FollowJointTrajectory
  joints: [t1_a2_shoulder_joint, t1_a2_elbow_joint, t1_a2_wrist_1_joint, t1_a2_wrist_2_joint, t1_a2_wrist_3_joint]

t2_a1_arm_controller:
  type: FollowJointTrajectory
  joints: [t2_a1_shoulder_joint, t2_a1_elbow_joint, t2_a1_wrist_1_joint, t2_a1_wrist_2_joint, t2_a1_wrist_3_joint]

t2_a2_arm_controller:
  type: FollowJointTrajectory
  joints: [t2_a2_shoulder_joint, t2_a2_elbow_joint, t2_a2_wrist_1_joint, t2_a2_wrist_2_joint, t2_a2_wrist_3_joint]
