# --- GLOBAL SETTINGS ---
octomap_frame: world
octomap_resolution: 0.02 # 1 cm resolution (The grid size)
max_range: 5.0

sensors:
  - default_sensor
  - kinect_depthimage
  - livox_lidar
default_sensor:
  far_clipping_plane_distance: 5.0
  filtered_cloud_topic: filtered_cloud
  image_topic: /head_mount_kinect/depth_registered/image_raw
  max_update_rate: 1.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.03
  padding_scale: 4.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.2
kinect_depthimage:
  far_clipping_plane_distance: 5.0
  filtered_cloud_topic: filtered_cloud
  image_topic: /head_mount_kinect/depth_registered/image_raw
  max_update_rate: 1.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.03
  padding_scale: 4.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.2
# --- SENSOR CONFIG ---
livox_lidar:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /livox/lidar
  filtered_cloud_topic: filtered_cloud_lidar

  # --- RANGE SETTINGS ---
  # Matches your room size. Ensure this hits the floor!
  max_range: 5.0 
  
  # Speed vs Accuracy: 1 is most accurate, but 2 or 4 is faster.
  # If ghosting continues, try changing this to 2.
  point_subsample: 4
  
  # --- CLEARING SETTINGS (The Ghost Killers) ---
  # 1. Update speed: Increased to 10Hz for faster reaction
  max_update_rate: 20.0
  
  # 2. Clipping: Start clearing immediately (5cm) out to the max range
  near_clipping_plane_distance: 0.05
  far_clipping_plane_distance: 5.0
  
  # 3. Shadow Threshold: 
  # 0.2 is safer than 0.01. It essentially says:
  # "If I see empty space with 20% confidence, CLEAR the obstacle."
  shadow_threshold: 0.2

  # --- SHAPE SETTINGS ---
  padding_offset: 0.01
  padding_scale: 1.0
  
  # (Optional) Standard parameters
  skip_invalid_points: false


